export const USER_ACTION_TYPES = {
  SET_CURRENT_USER: "user/SET_CURRENT_USER",
  POST_USER_START: "user/POST_USER_START",
  POST_USER_FAILED: "user/POST_USER_FAILED",
  LOGIN_USER_SUCCESS: "user/LOGIN_USER_SUCCESS",
  REGISTER_USER_SUCCESS: "user/REGISTER_USER_SUCCESS",
  SET_ERROR: "user/SET_ERROR",
};
