export const TASKS_ACTION_TYPES = {
  TASK_ACTION_START: "tasks/TASK_ACTION_START",
  TASK_ACTION_FAIL: "tasks/TASK_ACTION_FAIL",
  TASK_ACTION_SUCCESS: "tasks/TASK_ACTION_SUCCESS",
  SET_CURRENT_PAGE: "tasks/SET_CURRENT_PAGE",
  SET_PER_PAGE: "tasks/SET_PER_PAGE",
  SET_SORT: "tasks/SET_SORT",
  SET_TASKS: "tasks/SET_TASKS",
  SET_ERROR: "tasks/SET_ERROR",
};
