export const TASKS_ACTION_TYPES = {
  FETCH_TASKS_START: "tasks/FETCH_TASKS_START",
  FETCH_TASKS_SUCCESS: "tasks/FETCH_TASKS_SUCCESS",
  FETCH_TASKS_FAILED: "tasks/FETCH_TASKS_FAILED",
  SET_CURRENT_PAGE: "tasks/SET_CURRENT_PAGE",
  SET_PER_PAGE: "tasks/SET_PER_PAGE",
  SET_SORT: "tasks/SET_SORT",
};
