export const TASKS_ACTION_TYPES = {
  FETCH_TASKS_START: "tasks/FETCH_TASKS_START",
  FETCH_TASKS_SUCCESS: "tasks/FETCH_TASKS_SUCCESS",
  FETCH_TASKS_FAILED: "tasks/FETCH_TASKS_FAILED",
  ADD_TASK_START: "tasks/ADD_TASK_START",
  ADD_TASK_SUCCESS: "tasks/ADD_TASK_SUCCESS",
  ADD_TASK_FAILED: "tasks/ADD_TASK_FAILED",
  SET_CURRENT_PAGE: "tasks/SET_CURRENT_PAGE",
  SET_PER_PAGE: "tasks/SET_PER_PAGE",
  SET_SORT: "tasks/SET_SORT",
  SET_TASKS: "tasks/SET_TASKS",
};
